/*
 * Werewolf Engine
 *
 * This is a werewolf game engine for REST access. It is primarily developed for CPE200 class at Computer Engineering, Chiang Mai University.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: pruetboonma@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace DNWS.Werewolf 
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ChatMessage
    { 
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id")]
        public long? Id { get; set; }

        public long GameId {get; set; }

        /// <summary>
        /// Gets or Sets Player
        /// </summary>
        [DataMember(Name="playerid")]
        public long PlayerId { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [Required]
        [DataMember(Name="message")]
        public string Message { get; set; }
        /// <summary>
        /// Chat channel
        /// </summary>
        /// <value>Chat channel</value>
        public enum ChannelEnum
        { 
            [EnumMember(Value = "wolf")]
            WolfEnum = 1,
            
            [EnumMember(Value = "village")]
            VillageEnum = 2,
            [EnumMember(Value = "dead")]
            DeadEnum = 3,
            [EnumMember(Value = "jail")]
            JailEnum = 4
        }

        /// <summary>
        /// Chat channel
        /// </summary>
        /// <value>Chat channel</value>
        [DataMember(Name="channel")]
        public ChannelEnum? Channel { get; set; }
    }
}
