
/*
 * Werewolf Engine
 *
 * This is a werewolf game engine for REST access. It is primarily developed for CPE200 class at Computer Engineering, Chiang Mai University.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: pruetboonma@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace DNWS.Werewolf 
{ 
    /// <summary>
    /// 
    /// </summary>
    public partial class Game
    {
        private Player _enchanted = null;
        public Player Enchanted {get => _enchanted; set => _enchanted = value; }
        private Player _jailed = null;
        public Player Jailed {get => _jailed; set => _jailed = value;}
        private Player _kill_by_serial_killer = null;
        public Player KillBySerialKiller {get => _kill_by_serial_killer; set => _kill_by_serial_killer = value; }
        private Player _kill_by_wolf = null;
        public Player KillByWolf {set => _kill_by_wolf = value;}
        private Player _protected_by_bodyguard = null;
        public Player ProtectedByBodyguard {get => _protected_by_bodyguard; set => _protected_by_bodyguard = value;}
        private Player _healed_by_doctor = null;
        public Player HealedByDoctor {get => _healed_by_doctor; set => _healed_by_doctor = value;}
        private int _bodyguard_hit = 0;
        public int BodyguardHit {get => _bodyguard_hit; set => _bodyguard_hit = value;}
        private Player _target_by_head_hunter = null;
        public Player TargetByHeadHunter {get => _target_by_head_hunter; set => _target_by_head_hunter = value;}
        private Player _revive_by_medium = null;
        public Player ReviveByMedium {get => _revive_by_medium; set => _revive_by_medium = value;}
        private Dictionary<Player, Player> _dayVoteList;
        private Dictionary<Player, Player> _nightVoteList;
        public Dictionary<Player, Player> DayVoteList
        {
            get { return _dayVoteList;}
        }
        public Dictionary<Player, Player> NightVoteList
        {
            get { return _nightVoteList;}
        }
        public void ResetDayVoteList()
        {
            _dayVoteList = new Dictionary<Player, Player>();
        }
        public void ResetNightVoteList()
        {
            _nightVoteList = new Dictionary<Player, Player>();
        }
        public enum OutcomeEnum
        {
            VillagerWin = 1,
            WerewolfWin = 2,
            FoolWin = 3,
            HeadHunterWin = 4,
            SerialKillerWin = 5,
            NoWin = 6,
        }
        [NotMapped]
        [JsonProperty("Outcome")]
        public OutcomeEnum? Outcome {get; set;}
    }
}