/*
 * Werewolf Engine
 *
 * This is a werewolf game engine for REST access. It is primarily developed for CPE200 class at Computer Engineering, Chiang Mai University.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: pruetboonma@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations.Schema;
using Newtonsoft.Json.Converters;

namespace DNWS.Werewolf 
{ 
    /// <summary>
    /// 
    /// </summary>
    [Serializable]
    [DataContract]
    public class Role
    { 
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [Key]
        [DataMember(Name="id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [Required]
        [DataMember(Name="name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [DataMember(Name="actionrole")]
        public virtual ICollection<ActionRole> ActionRoles { get; set; }
        [NotMapped]
        [JsonProperty("actions")]
        public List<Action> Actions {get; set;}

        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        { 
            /// <summary>
            ///
            /// </summary>
            [EnumMember(Value = "Villager")]
            VillagerEnum = 1,
            
            /// <summary>
            ///
            /// </summary>
            [EnumMember(Value = "Wolf")]
            WolfEnum = 2,
            
            /// <summary>
            ///
            /// </summary>
            [EnumMember(Value = "Neutral")]
            NeutralEnum = 3,
        }
        [Required]
        [DataMember(Name="type")]
        public TypeEnum? Type { get; set; }
       public Role()
        {
            this.ActionRoles = new HashSet<ActionRole>();
        }
    }
}
